services:
  wifb-server:
    container_name: wifb_server
    image: dogwifbat-website
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "3000:3000"

    networks:
      - caddy_caddy-network

networks:
  caddy_caddy-network:
    external: true